apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfgmap1
  labels:
    {{- include "mychart.app" . | nindent 4 }}
data:
  myvalue: "Hello world"
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
  {{- include "mychart.app" . | nindent 2 }}
  salad: {{ .Values.global.salad }}
